package model.AM;

import model.VO.EmployeesViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 02 12:16:50 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl)findViewObject("CountriesView1");
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl)findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for EmpDetailsViewView1.
     * @return EmpDetailsViewView1
     */
    public ViewObjectImpl getEmpDetailsViewView1() {
        return (ViewObjectImpl)findViewObject("EmpDetailsViewView1");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeesView1() {
        return (EmployeesViewImpl)findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for JobHistoryView1.
     * @return JobHistoryView1
     */
    public ViewObjectImpl getJobHistoryView1() {
        return (ViewObjectImpl)findViewObject("JobHistoryView1");
    }

    /**
     * Container's getter for JobsView1.
     * @return JobsView1
     */
    public ViewObjectImpl getJobsView1() {
        return (ViewObjectImpl)findViewObject("JobsView1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl)findViewObject("LocationsView1");
    }

    /**
     * Container's getter for PsTxnView1.
     * @return PsTxnView1
     */
    public ViewObjectImpl getPsTxnView1() {
        return (ViewObjectImpl)findViewObject("PsTxnView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl)findViewObject("RegionsView1");
    }

    /**
     * Container's getter for CountriesView2.
     * @return CountriesView2
     */
    public ViewObjectImpl getCountriesView2() {
        return (ViewObjectImpl)findViewObject("CountriesView2");
    }

    /**
     * Container's getter for DepartmentsView2.
     * @return DepartmentsView2
     */
    public ViewObjectImpl getDepartmentsView2() {
        return (ViewObjectImpl)findViewObject("DepartmentsView2");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl)findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmpDetailsViewView2.
     * @return EmpDetailsViewView2
     */
    public ViewObjectImpl getEmpDetailsViewView2() {
        return (ViewObjectImpl)findViewObject("EmpDetailsViewView2");
    }

    /**
     * Container's getter for JobsView2.
     * @return JobsView2
     */
    public ViewObjectImpl getJobsView2() {
        return (ViewObjectImpl)findViewObject("JobsView2");
    }

    /**
     * Container's getter for JobHistoryView2.
     * @return JobHistoryView2
     */
    public ViewObjectImpl getJobHistoryView2() {
        return (ViewObjectImpl)findViewObject("JobHistoryView2");
    }

    /**
     * Container's getter for LocationsView2.
     * @return LocationsView2
     */
    public ViewObjectImpl getLocationsView2() {
        return (ViewObjectImpl)findViewObject("LocationsView2");
    }

    /**
     * Container's getter for PsTxnView2.
     * @return PsTxnView2
     */
    public ViewObjectImpl getPsTxnView2() {
        return (ViewObjectImpl)findViewObject("PsTxnView2");
    }

    /**
     * Container's getter for RegionsView2.
     * @return RegionsView2
     */
    public ViewObjectImpl getRegionsView2() {
        return (ViewObjectImpl)findViewObject("RegionsView2");
    }

    /**
     * Container's getter for DepartmentsView3.
     * @return DepartmentsView3
     */
    public ViewObjectImpl getDepartmentsView3() {
        return (ViewObjectImpl)findViewObject("DepartmentsView3");
    }

    /**
     * Container's getter for EmployeesView3.
     * @return EmployeesView3
     */
    public EmployeesViewImpl getEmployeesView3() {
        return (EmployeesViewImpl)findViewObject("EmployeesView3");
    }

    /**
     * Container's getter for EmployeesView4.
     * @return EmployeesView4
     */
    public EmployeesViewImpl getEmployeesView4() {
        return (EmployeesViewImpl)findViewObject("EmployeesView4");
    }

    /**
     * Container's getter for EmployeesView5.
     * @return EmployeesView5
     */
    public EmployeesViewImpl getEmployeesView5() {
        return (EmployeesViewImpl)findViewObject("EmployeesView5");
    }

    /**
     * Container's getter for JobHistoryView3.
     * @return JobHistoryView3
     */
    public ViewObjectImpl getJobHistoryView3() {
        return (ViewObjectImpl)findViewObject("JobHistoryView3");
    }

    /**
     * Container's getter for JobHistoryView4.
     * @return JobHistoryView4
     */
    public ViewObjectImpl getJobHistoryView4() {
        return (ViewObjectImpl)findViewObject("JobHistoryView4");
    }

    /**
     * Container's getter for JobHistoryView5.
     * @return JobHistoryView5
     */
    public ViewObjectImpl getJobHistoryView5() {
        return (ViewObjectImpl)findViewObject("JobHistoryView5");
    }

    /**
     * Container's getter for DepartmentsView4.
     * @return DepartmentsView4
     */
    public ViewObjectImpl getDepartmentsView4() {
        return (ViewObjectImpl)findViewObject("DepartmentsView4");
    }

    /**
     * Container's getter for LocationsView3.
     * @return LocationsView3
     */
    public ViewObjectImpl getLocationsView3() {
        return (ViewObjectImpl)findViewObject("LocationsView3");
    }

    /**
     * Container's getter for CountriesView3.
     * @return CountriesView3
     */
    public ViewObjectImpl getCountriesView3() {
        return (ViewObjectImpl)findViewObject("CountriesView3");
    }

    /**
     * Container's getter for LocationsView4.
     * @return LocationsView4
     */
    public ViewObjectImpl getLocationsView4() {
        return (ViewObjectImpl)findViewObject("LocationsView4");
    }

    /**
     * Container's getter for EmployeesView6.
     * @return EmployeesView6
     */
    public ViewObjectImpl getEmployeesView6() {
        return (ViewObjectImpl)findViewObject("EmployeesView6");
    }

    /**
     * Container's getter for JobHistoryView6.
     * @return JobHistoryView6
     */
    public ViewObjectImpl getJobHistoryView6() {
        return (ViewObjectImpl)findViewObject("JobHistoryView6");
    }

    /**
     * Container's getter for DepartmentsView5.
     * @return DepartmentsView5
     */
    public ViewObjectImpl getDepartmentsView5() {
        return (ViewObjectImpl)findViewObject("DepartmentsView5");
    }

    /**
     * Container's getter for EmployeesView7.
     * @return EmployeesView7
     */
    public ViewObjectImpl getEmployeesView7() {
        return (ViewObjectImpl)findViewObject("EmployeesView7");
    }

    /**
     * Container's getter for JobHistoryView7.
     * @return JobHistoryView7
     */
    public ViewObjectImpl getJobHistoryView7() {
        return (ViewObjectImpl)findViewObject("JobHistoryView7");
    }

    /**
     * Container's getter for EmployeesView8.
     * @return EmployeesView8
     */
    public ViewObjectImpl getEmployeesView8() {
        return (ViewObjectImpl)findViewObject("EmployeesView8");
    }

    /**
     * Container's getter for JobHistoryView8.
     * @return JobHistoryView8
     */
    public ViewObjectImpl getJobHistoryView8() {
        return (ViewObjectImpl)findViewObject("JobHistoryView8");
    }

    /**
     * Container's getter for DepartmentsView6.
     * @return DepartmentsView6
     */
    public ViewObjectImpl getDepartmentsView6() {
        return (ViewObjectImpl)findViewObject("DepartmentsView6");
    }

    /**
     * Container's getter for CountriesView4.
     * @return CountriesView4
     */
    public ViewObjectImpl getCountriesView4() {
        return (ViewObjectImpl)findViewObject("CountriesView4");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptMgrFkLink1");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for EmpJobFkLink1.
     * @return EmpJobFkLink1
     */
    public ViewLinkImpl getEmpJobFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpJobFkLink1");
    }

    /**
     * Container's getter for JhistDeptFkLink1.
     * @return JhistDeptFkLink1
     */
    public ViewLinkImpl getJhistDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistDeptFkLink1");
    }

    /**
     * Container's getter for JhistEmpFkLink1.
     * @return JhistEmpFkLink1
     */
    public ViewLinkImpl getJhistEmpFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistEmpFkLink1");
    }

    /**
     * Container's getter for JhistJobFkLink1.
     * @return JhistJobFkLink1
     */
    public ViewLinkImpl getJhistJobFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistJobFkLink1");
    }

    /**
     * Container's getter for DeptLocFkLink1.
     * @return DeptLocFkLink1
     */
    public ViewLinkImpl getDeptLocFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptLocFkLink1");
    }

    /**
     * Container's getter for LocCIdFkLink1.
     * @return LocCIdFkLink1
     */
    public ViewLinkImpl getLocCIdFkLink1() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink1");
    }

    /**
     * Container's getter for CountrRegFkLink1.
     * @return CountrRegFkLink1
     */
    public ViewLinkImpl getCountrRegFkLink1() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink1");
    }

    /**
     * Container's getter for LocCIdFkLink2.
     * @return LocCIdFkLink2
     */
    public ViewLinkImpl getLocCIdFkLink2() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink2");
    }

    /**
     * Container's getter for EmpDeptFkLink2.
     * @return EmpDeptFkLink2
     */
    public ViewLinkImpl getEmpDeptFkLink2() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink2");
    }

    /**
     * Container's getter for JhistDeptFkLink2.
     * @return JhistDeptFkLink2
     */
    public ViewLinkImpl getJhistDeptFkLink2() {
        return (ViewLinkImpl)findViewLink("JhistDeptFkLink2");
    }

    /**
     * Container's getter for DeptMgrFkLink2.
     * @return DeptMgrFkLink2
     */
    public ViewLinkImpl getDeptMgrFkLink2() {
        return (ViewLinkImpl)findViewLink("DeptMgrFkLink2");
    }

    /**
     * Container's getter for EmpManagerFkLink2.
     * @return EmpManagerFkLink2
     */
    public ViewLinkImpl getEmpManagerFkLink2() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink2");
    }

    /**
     * Container's getter for JhistEmpFkLink2.
     * @return JhistEmpFkLink2
     */
    public ViewLinkImpl getJhistEmpFkLink2() {
        return (ViewLinkImpl)findViewLink("JhistEmpFkLink2");
    }

    /**
     * Container's getter for EmpJobFkLink2.
     * @return EmpJobFkLink2
     */
    public ViewLinkImpl getEmpJobFkLink2() {
        return (ViewLinkImpl)findViewLink("EmpJobFkLink2");
    }

    /**
     * Container's getter for JhistJobFkLink2.
     * @return JhistJobFkLink2
     */
    public ViewLinkImpl getJhistJobFkLink2() {
        return (ViewLinkImpl)findViewLink("JhistJobFkLink2");
    }

    /**
     * Container's getter for DeptLocFkLink2.
     * @return DeptLocFkLink2
     */
    public ViewLinkImpl getDeptLocFkLink2() {
        return (ViewLinkImpl)findViewLink("DeptLocFkLink2");
    }

    /**
     * Container's getter for CountrRegFkLink2.
     * @return CountrRegFkLink2
     */
    public ViewLinkImpl getCountrRegFkLink2() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink2");
    }

    /**
     * Container's getter for DepartmentsEmployeeROVO1.
     * @return DepartmentsEmployeeROVO1
     */
    public ViewObjectImpl getDepartmentsEmployeeROVO1() {
        return (ViewObjectImpl)findViewObject("DepartmentsEmployeeROVO1");
    }
}
